### ISSUE TITLE
一人血书，求大佬出个Python3的版本

### ISSUE THREAD

**Issue by Pd1r** [boy-hack/w9scan#49]
感觉还是这个用起来顺手啊 [手动狗头]

**Comment by boy-hack** [comment]
可以尝试w13scan

**Comment by Pd1r** [comment]
我看了下readme，貌似没办法像w9scan一样，指定扫描 某个插件或者某类所有的插件
w9scan 可以 -s 泛搜索 有没有插件
而且感觉使用时需要输入的参数，也相比其他参数更简洁 就一个 -u http://xx.xx.xx -p weblogic
